spring:
  application:
    name: MyShowList

service:
  api:
    root-path: /api/v1
    show:
      path: /shows
    register:
      path: /register
    login:
      path: /login
  jwt:
    base64-secret: ${JWT_SECRET}
    expiration: 1h
