spring:
  application:
    name: MyShowList

service:
  api:
    root-path: /api/v1
    show:
      path: ${service.api.root-path}/shows
    register:
      path: ${service.api.root-path}/register
    login:
      path: ${service.api.root-path}/login
    user-show:
      path: ${service.api.root-path}/user-shows
    review:
      path: ${service.api.show.path}/{showId}/reviews
  jwt:
    base64-secret: ${JWT_SECRET}
    expiration: 1h
